# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Локальные unix-сокет подключения (например, psql внутри самого контейнера) — без пароля
local   all             all                                     trust

# Подключения с localhost хост-машины (если подключаетесь psql/DBeaver напрямую с компьютера)
host    all             all             127.0.0.1/32            scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# Подключения из docker-сети (ваш API-контейнер стучится сюда по паролю)
host    all             all             0.0.0.0/0               scram-sha-256